### ISSUE TITLE
DataExtractor and French language

### ISSUE THREAD

**Issue by sercankd** [Arctium-Emulation/Tools#4]
it doesnt work well, cant extract itemsearchname.dbc i think it doesnt support utf8

`Unhandled Exception: System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.Inflater.DecodeDynamicBlockHeader()
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at CASC_Lib.CASC.Handlers.DataFile.LoadBLTEEntry(IndexEntry idxEntry, BinaryReader readStream)
   at CASC_Lib.CASC.Handlers.CASCHandler.ReadFile(RootEntry[] rootEntries, Locales locales)
   at DataExtractor.Program.ExtractClientDBData()
   at DataExtractor.Program.Main(String[] args)`

**Comment by Fabi** [comment]
Which client? 7.1.0?
I just installed french on 7.1.0 and 7.1.5 where it works fine. Have you tried to repair your client?

**Comment by sercankd** [comment]
7.0.3, can you give me itemsearchname.dbc, because its only file i need.

**Comment by Fabi** [comment]
If it's not working with frFR, your installation is broken. You should download the latest live client and extract the db2 file there.

**Comment by sercankd** [comment]
it works fine with enUS in same client, it doesnt work when i change it to FR
